export declare const redirectWelcome: (req: any, res: any) => void;
export declare const welcome: (req: any, res: any) => void;
export declare const drivingDirections: (req: any, res: any) => Promise<void>;
export declare const transferBellevue: (req: any, res: any) => Promise<void>;
export declare const transferNorthgate: (req: any, res: any) => Promise<void>;
export declare const enrollOffers: (req: any, res: any) => Promise<void>;
export declare const appointment: (req: any, res: any) => Promise<void>;
export declare const advisor: (req: any, res: any) => Promise<void>;
export declare const requestInformation: (req: any, res: any) => Promise<void>;
export declare const listenVoicemail: (req: any, res: any) => Promise<void>;
//# sourceMappingURL=handler.d.ts.map