import * as admin from 'firebase-admin';
export declare const NODE_ENV: string;
export declare const FIREBASE_CONFIG: string | undefined;
export declare const GCLOUD_PROJECT: string | undefined;
export declare const FUNCTIONS_EMULATOR: string | undefined;
export declare let FIREBASE_ENDPOINT: string;
export declare let FIRESTORE_EMULATOR_HOST: string;
export declare let FIREBASE_ADMIN_SDK: string;
export declare let FIREBASE_KEYPATH: string;
export declare let FIREBASE_DB_PATH: string;
export declare let FIREBASE_STORAGE: string;
export declare const fireapp: admin.app.App;
export declare const PUBSUB_TOPIC = "projects/example/topics/messages";
export declare const url_endpoint: string;
export declare const firebase: typeof admin;
export declare const firebaseTimestamp: typeof FirebaseFirestore.Timestamp;
export declare const auth: admin.auth.Auth;
export declare const db: FirebaseFirestore.Firestore;
export declare const storage: import("@google-cloud/storage/build/src/bucket").Bucket;
//# sourceMappingURL=fireapp.d.ts.map