export declare const replaceUndefinedWithBlank: (value: string | undefined) => string;
export declare const reUnBLANK: (value: string | undefined) => string;
export declare const isBlank: (value: string) => boolean;
export declare const isBLK: (value: string) => boolean;
export declare const getPropValue: (obj: any, key: any) => any;
export declare const removeEmpty: (obj: any) => any;
export declare const re: (obj: any) => any;
export declare const rmUn: (obj: any) => void;
export declare const e: (object: any) => any;
export declare const rmUndefinedProperty: <T extends object, K extends keyof T>(obj: T, key: K) => Pick<T, Exclude<keyof T, K>>;
export declare const makeArray: <T>(x: T) => T[];
//# sourceMappingURL=checkUndefinedValue.d.ts.map